acme_store_homepage:
    pattern:  /
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_store_products:
    pattern:  /products
    defaults: { _controller: AcmeStoreBundle:Default:showProducts }

acme_store_categories:
    pattern:  /categories
    defaults: { _controller: AcmeStoreBundle:Default:showCategories }

acme_store_product_description:
    pattern:  /description/product/{id}
    defaults: { _controller: AcmeStoreBundle:Default:descriptionProduct }

acme_store_all_products_of_category:
    pattern:  /description/category/{id}
    defaults: { _controller: AcmeStoreBundle:Default:allProductsOfCategory }

acme_store_create:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:create }

acme_store_show:
    pattern:  /show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }

acme_store_update:
    pattern:  /update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update }

acme_store_select:
    pattern:  /select
    defaults: { _controller: AcmeStoreBundle:Default:select }

acme_store_select:
    pattern:  /findall
    defaults: { _controller: AcmeStoreBundle:Default:findAll }